# Generated by Django 2.0.6 on 2018-06-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='suborder',
        ),
        migrations.RemoveField(
            model_name='trna',
            name='suborder',
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='subclass',
            field=models.CharField(db_column='class', max_length=50, verbose_name='class'),
        ),
    ]
