# Generated by Django 2.0.6 on 2018-06-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_auto_20180615_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trna',
            name='p1',
            field=models.CharField(default='-', max_length=1, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p10',
            field=models.CharField(default='-', max_length=1, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p10_25',
            field=models.CharField(default='-:-', max_length=3, verbose_name='10:25'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p10_45',
            field=models.CharField(default='-:-', max_length=3, verbose_name='10:45'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p11',
            field=models.CharField(default='-', max_length=1, verbose_name='11'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p11_24',
            field=models.CharField(default='-:-', max_length=3, verbose_name='11:24'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p12',
            field=models.CharField(default='-', max_length=1, verbose_name='12'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p12_23',
            field=models.CharField(default='-:-', max_length=3, verbose_name='12:23'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p13',
            field=models.CharField(default='-', max_length=1, verbose_name='13'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p13_22',
            field=models.CharField(default='-:-', max_length=3, verbose_name='13:22'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p14',
            field=models.CharField(default='-', max_length=1, verbose_name='14'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p15',
            field=models.CharField(default='-', max_length=1, verbose_name='15'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p15_48',
            field=models.CharField(default='-:-', max_length=3, verbose_name='15:48'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p16',
            field=models.CharField(default='-', max_length=1, verbose_name='16'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p17',
            field=models.CharField(default='-', max_length=1, verbose_name='17'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p17a',
            field=models.CharField(default='-', max_length=1, verbose_name='17a'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p18',
            field=models.CharField(default='-', max_length=1, verbose_name='18'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p18_55',
            field=models.CharField(default='-:-', max_length=3, verbose_name='18:55'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p19',
            field=models.CharField(default='-', max_length=1, verbose_name='19'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p19_56',
            field=models.CharField(default='-:-', max_length=3, verbose_name='19:56'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p1_72',
            field=models.CharField(default='-:-', max_length=3, verbose_name='1:72'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p2',
            field=models.CharField(default='-', max_length=1, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p20',
            field=models.CharField(default='-', max_length=1, verbose_name='20'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p20a',
            field=models.CharField(default='-', max_length=1, verbose_name='20a'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p20b',
            field=models.CharField(default='-', max_length=1, verbose_name='20b'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p21',
            field=models.CharField(default='-', max_length=1, verbose_name='21'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p22',
            field=models.CharField(default='-', max_length=1, verbose_name='22'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p22_46',
            field=models.CharField(default='-:-', max_length=3, verbose_name='22:46'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p23',
            field=models.CharField(default='-', max_length=1, verbose_name='23'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p24',
            field=models.CharField(default='-', max_length=1, verbose_name='24'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p25',
            field=models.CharField(default='-', max_length=1, verbose_name='25'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p26',
            field=models.CharField(default='-', max_length=1, verbose_name='26'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p26_44',
            field=models.CharField(default='-:-', max_length=3, verbose_name='26:44'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p27',
            field=models.CharField(default='-', max_length=1, verbose_name='27'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p27_43',
            field=models.CharField(default='-:-', max_length=3, verbose_name='27:43'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p28',
            field=models.CharField(default='-', max_length=1, verbose_name='28'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p28_42',
            field=models.CharField(default='-:-', max_length=3, verbose_name='28:42'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p29',
            field=models.CharField(default='-', max_length=1, verbose_name='29'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p29_41',
            field=models.CharField(default='-:-', max_length=3, verbose_name='29:41'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p2_71',
            field=models.CharField(default='-:-', max_length=3, verbose_name='2:71'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p3',
            field=models.CharField(default='-', max_length=1, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p30',
            field=models.CharField(default='-', max_length=1, verbose_name='30'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p30_40',
            field=models.CharField(default='-:-', max_length=3, verbose_name='30:40'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p31',
            field=models.CharField(default='-', max_length=1, verbose_name='31'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p31_39',
            field=models.CharField(default='-:-', max_length=3, verbose_name='31:39'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p32',
            field=models.CharField(default='-', max_length=1, verbose_name='32'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p33',
            field=models.CharField(default='-', max_length=1, verbose_name='33'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p34',
            field=models.CharField(default='-', max_length=1, verbose_name='34'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p35',
            field=models.CharField(default='-', max_length=1, verbose_name='35'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p36',
            field=models.CharField(default='-', max_length=1, verbose_name='36'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p37',
            field=models.CharField(default='-', max_length=1, verbose_name='37'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p38',
            field=models.CharField(default='-', max_length=1, verbose_name='38'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p39',
            field=models.CharField(default='-', max_length=1, verbose_name='39'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p3_70',
            field=models.CharField(default='-:-', max_length=3, verbose_name='3:70'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p4',
            field=models.CharField(default='-', max_length=1, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p40',
            field=models.CharField(default='-', max_length=1, verbose_name='40'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p41',
            field=models.CharField(default='-', max_length=1, verbose_name='41'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p42',
            field=models.CharField(default='-', max_length=1, verbose_name='42'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p43',
            field=models.CharField(default='-', max_length=1, verbose_name='43'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p44',
            field=models.CharField(default='-', max_length=1, verbose_name='44'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p45',
            field=models.CharField(default='-', max_length=1, verbose_name='45'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p46',
            field=models.CharField(default='-', max_length=1, verbose_name='46'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p47',
            field=models.CharField(default='-', max_length=1, verbose_name='47'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p48',
            field=models.CharField(default='-', max_length=1, verbose_name='48'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p49',
            field=models.CharField(default='-', max_length=1, verbose_name='49'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p49_65',
            field=models.CharField(default='-:-', max_length=3, verbose_name='49:65'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p4_69',
            field=models.CharField(default='-:-', max_length=3, verbose_name='4:69'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p5',
            field=models.CharField(default='-', max_length=1, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p50',
            field=models.CharField(default='-', max_length=1, verbose_name='50'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p50_64',
            field=models.CharField(default='-:-', max_length=3, verbose_name='50:64'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p51',
            field=models.CharField(default='-', max_length=1, verbose_name='51'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p51_63',
            field=models.CharField(default='-:-', max_length=3, verbose_name='51:63'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p52',
            field=models.CharField(default='-', max_length=1, verbose_name='52'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p52_62',
            field=models.CharField(default='-:-', max_length=3, verbose_name='52:62'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p53',
            field=models.CharField(default='-', max_length=1, verbose_name='53'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p53_61',
            field=models.CharField(default='-:-', max_length=3, verbose_name='53:61'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p54',
            field=models.CharField(default='-', max_length=1, verbose_name='54'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p54_58',
            field=models.CharField(default='-:-', max_length=3, verbose_name='54:58'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p55',
            field=models.CharField(default='-', max_length=1, verbose_name='55'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p56',
            field=models.CharField(default='-', max_length=1, verbose_name='56'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p57',
            field=models.CharField(default='-', max_length=1, verbose_name='57'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p58',
            field=models.CharField(default='-', max_length=1, verbose_name='58'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p59',
            field=models.CharField(default='-', max_length=1, verbose_name='59'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p5_68',
            field=models.CharField(default='-:-', max_length=3, verbose_name='5:68'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p6',
            field=models.CharField(default='-', max_length=1, verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p60',
            field=models.CharField(default='-', max_length=1, verbose_name='60'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p61',
            field=models.CharField(default='-', max_length=1, verbose_name='61'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p62',
            field=models.CharField(default='-', max_length=1, verbose_name='62'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p63',
            field=models.CharField(default='-', max_length=1, verbose_name='63'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p64',
            field=models.CharField(default='-', max_length=1, verbose_name='64'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p65',
            field=models.CharField(default='-', max_length=1, verbose_name='65'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p66',
            field=models.CharField(default='-', max_length=1, verbose_name='66'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p67',
            field=models.CharField(default='-', max_length=1, verbose_name='67'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p68',
            field=models.CharField(default='-', max_length=1, verbose_name='68'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p69',
            field=models.CharField(default='-', max_length=1, verbose_name='69'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p6_67',
            field=models.CharField(default='-:-', max_length=3, verbose_name='6:67'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p7',
            field=models.CharField(default='-', max_length=1, verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p70',
            field=models.CharField(default='-', max_length=1, verbose_name='70'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p71',
            field=models.CharField(default='-', max_length=1, verbose_name='71'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p72',
            field=models.CharField(default='-', max_length=1, verbose_name='72'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p73',
            field=models.CharField(default='-', max_length=1, verbose_name='73'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p74',
            field=models.CharField(default='-', max_length=1, verbose_name='74'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p75',
            field=models.CharField(default='-', max_length=1, verbose_name='75'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p76',
            field=models.CharField(default='-', max_length=1, verbose_name='76'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p7_66',
            field=models.CharField(default='-:-', max_length=3, verbose_name='7:66'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p8',
            field=models.CharField(default='-', max_length=1, verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p8_14',
            field=models.CharField(default='-:-', max_length=1, verbose_name='8:14'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p9',
            field=models.CharField(default='-', max_length=1, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='p9_23',
            field=models.CharField(default='-:-', max_length=3, verbose_name='9:23'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV1',
            field=models.CharField(default='-', max_length=1, verbose_name='V1'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV11',
            field=models.CharField(default='-', max_length=1, verbose_name='V11'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV11_V21',
            field=models.CharField(default='-:-', max_length=3, verbose_name='V11:V21'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV12',
            field=models.CharField(default='-', max_length=1, verbose_name='V12'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV12_V22',
            field=models.CharField(default='-:-', max_length=3, verbose_name='V12:V22'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV13',
            field=models.CharField(default='-', max_length=1, verbose_name='V13'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV13_V23',
            field=models.CharField(default='-:-', max_length=3, verbose_name='V13:V23'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV14',
            field=models.CharField(default='-', max_length=1, verbose_name='V14'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV14_V24',
            field=models.CharField(default='-:-', max_length=3, verbose_name='V14:V24'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV15',
            field=models.CharField(default='-', max_length=1, verbose_name='V15'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV15_V25',
            field=models.CharField(default='-:-', max_length=3, verbose_name='V15:V25'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV16',
            field=models.CharField(default='-', max_length=1, verbose_name='V16'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV16_V26',
            field=models.CharField(default='-:-', max_length=3, verbose_name='V16:V26'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV17',
            field=models.CharField(default='-', max_length=1, verbose_name='V17'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV17_V27',
            field=models.CharField(default='-:-', max_length=3, verbose_name='V17:V27'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV2',
            field=models.CharField(default='-', max_length=1, verbose_name='V2'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV21',
            field=models.CharField(default='-', max_length=1, verbose_name='V21'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV22',
            field=models.CharField(default='-', max_length=1, verbose_name='V22'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV23',
            field=models.CharField(default='-', max_length=1, verbose_name='V23'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV24',
            field=models.CharField(default='-', max_length=1, verbose_name='V24'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV25',
            field=models.CharField(default='-', max_length=1, verbose_name='V25'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV26',
            field=models.CharField(default='-', max_length=1, verbose_name='V26'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV27',
            field=models.CharField(default='-', max_length=1, verbose_name='V27'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV3',
            field=models.CharField(default='-', max_length=1, verbose_name='V3'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV4',
            field=models.CharField(default='-', max_length=1, verbose_name='V4'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='pV5',
            field=models.CharField(default='-', max_length=1, verbose_name='V5'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='taxclass',
            field=models.CharField(db_column='class', max_length=50, verbose_name='class'),
        ),
    ]
