# Generated by Django 2.0.6 on 2018-06-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_auto_20180615_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consensus', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10)),
                ('isotype', models.CharField(max_length=3)),
                ('clade', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='trna',
            name='best_model',
            field=models.CharField(choices=[('Ala', 'Ala'), ('Arg', 'Arg'), ('Asn', 'Asn'), ('Asp', 'Asp'), ('Cys', 'Cys'), ('Gln', 'Gln'), ('Glu', 'Glu'), ('Gly', 'Gly'), ('His', 'His'), ('Ile', 'Ile'), ('iMet', 'iMet'), ('Leu', 'Leu'), ('Lys', 'Lys'), ('Met', 'Met'), ('Phe', 'Phe'), ('Pro', 'Pro'), ('Ser', 'Ser'), ('SeC', 'SeC'), ('Thr', 'Thr'), ('Trp', 'Trp'), ('Tyr', 'Tyr'), ('Und', 'Und'), ('Val', 'Val')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trna',
            name='isotype',
            field=models.CharField(choices=[('Ala', 'Ala'), ('Arg', 'Arg'), ('Asn', 'Asn'), ('Asp', 'Asp'), ('Cys', 'Cys'), ('Gln', 'Gln'), ('Glu', 'Glu'), ('Gly', 'Gly'), ('His', 'His'), ('Ile', 'Ile'), ('iMet', 'iMet'), ('Leu', 'Leu'), ('Lys', 'Lys'), ('Met', 'Met'), ('Phe', 'Phe'), ('Pro', 'Pro'), ('Ser', 'Ser'), ('SeC', 'SeC'), ('Thr', 'Thr'), ('Trp', 'Trp'), ('Tyr', 'Tyr'), ('Und', 'Und'), ('Val', 'Val')], max_length=3),
        ),
    ]
