# Generated by Django 2.0.6 on 2018-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_auto_20180618_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('isotype', models.CharField(max_length=3)),
                ('clade', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=20)),
                ('feature', models.CharField(max_length=3)),
                ('A', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('U', models.IntegerField(default=0)),
                ('absent', models.IntegerField(db_column='-', default=0)),
                ('AU', models.IntegerField(db_column='A:U', verbose_name='A:U')),
                ('UA', models.IntegerField(db_column='U:A', verbose_name='U:A')),
                ('GC', models.IntegerField(db_column='G:C', verbose_name='G:C')),
                ('CG', models.IntegerField(db_column='C:G', verbose_name='C:G')),
                ('GU', models.IntegerField(db_column='G:U', verbose_name='G:U')),
                ('UG', models.IntegerField(db_column='U:G', verbose_name='U:G')),
                ('AA', models.IntegerField(db_column='A:A', verbose_name='A:A')),
                ('AC', models.IntegerField(db_column='A:C', verbose_name='A:C')),
                ('AG', models.IntegerField(db_column='A:G', verbose_name='A:G')),
                ('CA', models.IntegerField(db_column='C:A', verbose_name='C:A')),
                ('CC', models.IntegerField(db_column='C:C', verbose_name='C:C')),
                ('CU', models.IntegerField(db_column='C:U', verbose_name='C:U')),
                ('GA', models.IntegerField(db_column='G:A', verbose_name='G:A')),
                ('GG', models.IntegerField(db_column='G:G', verbose_name='G:G')),
                ('UC', models.IntegerField(db_column='U:C', verbose_name='U:C')),
                ('UU', models.IntegerField(db_column='U:U', verbose_name='U:U')),
                ('AM', models.IntegerField(db_column='A:-', verbose_name='A:-')),
                ('CM', models.IntegerField(db_column='C:-', verbose_name='C:-')),
                ('GM', models.IntegerField(db_column='G:-', verbose_name='G:-')),
                ('UM', models.IntegerField(db_column='U:-', verbose_name='U:-')),
                ('MA', models.IntegerField(db_column='-:A', verbose_name='-:A')),
                ('MC', models.IntegerField(db_column='-:C', verbose_name='-:C')),
                ('MG', models.IntegerField(db_column='-:G', verbose_name='-:G')),
                ('MU', models.IntegerField(db_column='-:U', verbose_name='-:U')),
                ('MM', models.IntegerField(db_column='-:-', verbose_name='-:-')),
            ],
        ),
        migrations.RemoveField(
            model_name='consensus',
            name='consensus',
        ),
        migrations.RemoveField(
            model_name='consensus',
            name='position',
        ),
        migrations.AddField(
            model_name='consensus',
            name='p1',
            field=models.CharField(default='N', max_length=20, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p10',
            field=models.CharField(default='N', max_length=20, verbose_name='10'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p10_25',
            field=models.CharField(default='N:N', max_length=20, verbose_name='10:25'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p10_45',
            field=models.CharField(default='N:N', max_length=20, verbose_name='10:45'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p11',
            field=models.CharField(default='N', max_length=20, verbose_name='11'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p11_24',
            field=models.CharField(default='N:N', max_length=20, verbose_name='11:24'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p12',
            field=models.CharField(default='N', max_length=20, verbose_name='12'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p12_23',
            field=models.CharField(default='N:N', max_length=20, verbose_name='12:23'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p13',
            field=models.CharField(default='N', max_length=20, verbose_name='13'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p13_22',
            field=models.CharField(default='N:N', max_length=20, verbose_name='13:22'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p14',
            field=models.CharField(default='N', max_length=20, verbose_name='14'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p15',
            field=models.CharField(default='N', max_length=20, verbose_name='15'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p15_48',
            field=models.CharField(default='N:N', max_length=20, verbose_name='15:48'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p16',
            field=models.CharField(default='N', max_length=20, verbose_name='16'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p17',
            field=models.CharField(default='N', max_length=20, verbose_name='17'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p17a',
            field=models.CharField(default='N', max_length=20, verbose_name='17a'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p18',
            field=models.CharField(default='N', max_length=20, verbose_name='18'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p18_55',
            field=models.CharField(default='N:N', max_length=20, verbose_name='18:55'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p19',
            field=models.CharField(default='N', max_length=20, verbose_name='19'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p19_56',
            field=models.CharField(default='N:N', max_length=20, verbose_name='19:56'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p1_72',
            field=models.CharField(default='N:N', max_length=20, verbose_name='1:72'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p2',
            field=models.CharField(default='N', max_length=20, verbose_name='2'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p20',
            field=models.CharField(default='N', max_length=20, verbose_name='20'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p20a',
            field=models.CharField(default='N', max_length=20, verbose_name='20a'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p20b',
            field=models.CharField(default='N', max_length=20, verbose_name='20b'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p21',
            field=models.CharField(default='N', max_length=20, verbose_name='21'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p22',
            field=models.CharField(default='N', max_length=20, verbose_name='22'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p22_46',
            field=models.CharField(default='N:N', max_length=20, verbose_name='22:46'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p23',
            field=models.CharField(default='N', max_length=20, verbose_name='23'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p24',
            field=models.CharField(default='N', max_length=20, verbose_name='24'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p25',
            field=models.CharField(default='N', max_length=20, verbose_name='25'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p26',
            field=models.CharField(default='N', max_length=20, verbose_name='26'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p26_44',
            field=models.CharField(default='N:N', max_length=20, verbose_name='26:44'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p27',
            field=models.CharField(default='N', max_length=20, verbose_name='27'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p27_43',
            field=models.CharField(default='N:N', max_length=20, verbose_name='27:43'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p28',
            field=models.CharField(default='N', max_length=20, verbose_name='28'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p28_42',
            field=models.CharField(default='N:N', max_length=20, verbose_name='28:42'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p29',
            field=models.CharField(default='N', max_length=20, verbose_name='29'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p29_41',
            field=models.CharField(default='N:N', max_length=20, verbose_name='29:41'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p2_71',
            field=models.CharField(default='N:N', max_length=20, verbose_name='2:71'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p3',
            field=models.CharField(default='N', max_length=20, verbose_name='3'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p30',
            field=models.CharField(default='N', max_length=20, verbose_name='30'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p30_40',
            field=models.CharField(default='N:N', max_length=20, verbose_name='30:40'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p31',
            field=models.CharField(default='N', max_length=20, verbose_name='31'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p31_39',
            field=models.CharField(default='N:N', max_length=20, verbose_name='31:39'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p32',
            field=models.CharField(default='N', max_length=20, verbose_name='32'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p33',
            field=models.CharField(default='N', max_length=20, verbose_name='33'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p34',
            field=models.CharField(default='N', max_length=20, verbose_name='34'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p35',
            field=models.CharField(default='N', max_length=20, verbose_name='35'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p36',
            field=models.CharField(default='N', max_length=20, verbose_name='36'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p37',
            field=models.CharField(default='N', max_length=20, verbose_name='37'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p38',
            field=models.CharField(default='N', max_length=20, verbose_name='38'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p39',
            field=models.CharField(default='N', max_length=20, verbose_name='39'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p3_70',
            field=models.CharField(default='N:N', max_length=20, verbose_name='3:70'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p4',
            field=models.CharField(default='N', max_length=20, verbose_name='4'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p40',
            field=models.CharField(default='N', max_length=20, verbose_name='40'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p41',
            field=models.CharField(default='N', max_length=20, verbose_name='41'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p42',
            field=models.CharField(default='N', max_length=20, verbose_name='42'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p43',
            field=models.CharField(default='N', max_length=20, verbose_name='43'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p44',
            field=models.CharField(default='N', max_length=20, verbose_name='44'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p45',
            field=models.CharField(default='N', max_length=20, verbose_name='45'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p46',
            field=models.CharField(default='N', max_length=20, verbose_name='46'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p47',
            field=models.CharField(default='N', max_length=20, verbose_name='47'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p48',
            field=models.CharField(default='N', max_length=20, verbose_name='48'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p49',
            field=models.CharField(default='N', max_length=20, verbose_name='49'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p49_65',
            field=models.CharField(default='N:N', max_length=20, verbose_name='49:65'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p4_69',
            field=models.CharField(default='N:N', max_length=20, verbose_name='4:69'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p5',
            field=models.CharField(default='N', max_length=20, verbose_name='5'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p50',
            field=models.CharField(default='N', max_length=20, verbose_name='50'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p50_64',
            field=models.CharField(default='N:N', max_length=20, verbose_name='50:64'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p51',
            field=models.CharField(default='N', max_length=20, verbose_name='51'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p51_63',
            field=models.CharField(default='N:N', max_length=20, verbose_name='51:63'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p52',
            field=models.CharField(default='N', max_length=20, verbose_name='52'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p52_62',
            field=models.CharField(default='N:N', max_length=20, verbose_name='52:62'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p53',
            field=models.CharField(default='N', max_length=20, verbose_name='53'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p53_61',
            field=models.CharField(default='N:N', max_length=20, verbose_name='53:61'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p54',
            field=models.CharField(default='N', max_length=20, verbose_name='54'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p54_58',
            field=models.CharField(default='N:N', max_length=20, verbose_name='54:58'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p55',
            field=models.CharField(default='N', max_length=20, verbose_name='55'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p56',
            field=models.CharField(default='N', max_length=20, verbose_name='56'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p57',
            field=models.CharField(default='N', max_length=20, verbose_name='57'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p58',
            field=models.CharField(default='N', max_length=20, verbose_name='58'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p59',
            field=models.CharField(default='N', max_length=20, verbose_name='59'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p5_68',
            field=models.CharField(default='N:N', max_length=20, verbose_name='5:68'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p6',
            field=models.CharField(default='N', max_length=20, verbose_name='6'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p60',
            field=models.CharField(default='N', max_length=20, verbose_name='60'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p61',
            field=models.CharField(default='N', max_length=20, verbose_name='61'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p62',
            field=models.CharField(default='N', max_length=20, verbose_name='62'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p63',
            field=models.CharField(default='N', max_length=20, verbose_name='63'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p64',
            field=models.CharField(default='N', max_length=20, verbose_name='64'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p65',
            field=models.CharField(default='N', max_length=20, verbose_name='65'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p66',
            field=models.CharField(default='N', max_length=20, verbose_name='66'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p67',
            field=models.CharField(default='N', max_length=20, verbose_name='67'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p68',
            field=models.CharField(default='N', max_length=20, verbose_name='68'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p69',
            field=models.CharField(default='N', max_length=20, verbose_name='69'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p6_67',
            field=models.CharField(default='N:N', max_length=20, verbose_name='6:67'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p7',
            field=models.CharField(default='N', max_length=20, verbose_name='7'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p70',
            field=models.CharField(default='N', max_length=20, verbose_name='70'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p71',
            field=models.CharField(default='N', max_length=20, verbose_name='71'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p72',
            field=models.CharField(default='N', max_length=20, verbose_name='72'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p73',
            field=models.CharField(default='N', max_length=20, verbose_name='73'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p7_66',
            field=models.CharField(default='N:N', max_length=20, verbose_name='7:66'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p8',
            field=models.CharField(default='N', max_length=20, verbose_name='8'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p8_14',
            field=models.CharField(default='N:N', max_length=20, verbose_name='8:14'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p9',
            field=models.CharField(default='N', max_length=20, verbose_name='9'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='p9_23',
            field=models.CharField(default='N:N', max_length=20, verbose_name='9:23'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV1',
            field=models.CharField(default='N', max_length=20, verbose_name='V1'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV11',
            field=models.CharField(default='N', max_length=20, verbose_name='V11'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV11_V21',
            field=models.CharField(default='N:N', max_length=20, verbose_name='V11:V21'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV12',
            field=models.CharField(default='N', max_length=20, verbose_name='V12'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV12_V22',
            field=models.CharField(default='N:N', max_length=20, verbose_name='V12:V22'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV13',
            field=models.CharField(default='N', max_length=20, verbose_name='V13'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV13_V23',
            field=models.CharField(default='N:N', max_length=20, verbose_name='V13:V23'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV14',
            field=models.CharField(default='N', max_length=20, verbose_name='V14'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV14_V24',
            field=models.CharField(default='N:N', max_length=20, verbose_name='V14:V24'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV15',
            field=models.CharField(default='N', max_length=20, verbose_name='V15'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV15_V25',
            field=models.CharField(default='N:N', max_length=20, verbose_name='V15:V25'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV16',
            field=models.CharField(default='N', max_length=20, verbose_name='V16'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV16_V26',
            field=models.CharField(default='N:N', max_length=20, verbose_name='V16:V26'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV17',
            field=models.CharField(default='N', max_length=20, verbose_name='V17'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV17_V27',
            field=models.CharField(default='N:N', max_length=20, verbose_name='V17:V27'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV2',
            field=models.CharField(default='N', max_length=20, verbose_name='V2'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV21',
            field=models.CharField(default='N', max_length=20, verbose_name='V21'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV22',
            field=models.CharField(default='N', max_length=20, verbose_name='V22'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV23',
            field=models.CharField(default='N', max_length=20, verbose_name='V23'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV24',
            field=models.CharField(default='N', max_length=20, verbose_name='V24'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV25',
            field=models.CharField(default='N', max_length=20, verbose_name='V25'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV26',
            field=models.CharField(default='N', max_length=20, verbose_name='V26'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV27',
            field=models.CharField(default='N', max_length=20, verbose_name='V27'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV3',
            field=models.CharField(default='N', max_length=20, verbose_name='V3'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV4',
            field=models.CharField(default='N', max_length=20, verbose_name='V4'),
        ),
        migrations.AddField(
            model_name='consensus',
            name='pV5',
            field=models.CharField(default='N', max_length=20, verbose_name='V5'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='isotype',
            field=models.CharField(choices=[('Ala', 'Ala'), ('Arg', 'Arg'), ('Asn', 'Asn'), ('Asp', 'Asp'), ('Cys', 'Cys'), ('Gln', 'Gln'), ('Glu', 'Glu'), ('Gly', 'Gly'), ('His', 'His'), ('Ile', 'Ile'), ('iMet', 'iMet'), ('Leu', 'Leu'), ('Lys', 'Lys'), ('Met', 'Met'), ('Phe', 'Phe'), ('Pro', 'Pro'), ('Ser', 'Ser'), ('SeC', 'SeC'), ('Thr', 'Thr'), ('Trp', 'Trp'), ('Tyr', 'Tyr'), ('Und', 'Und'), ('Val', 'Val')], max_length=4),
        ),
    ]
