# Generated by Django 2.0.6 on 2018-06-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_auto_20180619_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('position', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
    ]
