# Generated by Django 2.0.6 on 2018-07-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_auto_20180622_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomy',
            old_name='assembly',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='kingdom',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='order',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='phylum',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='species',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='subclass',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='subkingdom',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='subphylum',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='taxclass',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='varietas',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
