# Generated by Django 2.0.6 on 2018-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0011_auto_20180724_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='trna',
            name='family',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
