# Generated by Django 2.0.6 on 2018-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0012_trna_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freq',
            name='clade',
        ),
        migrations.RemoveField(
            model_name='freq',
            name='rank',
        ),
        migrations.AddField(
            model_name='consensus',
            name='taxid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freq',
            name='taxid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freq',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freq',
            name='AA',
            field=models.IntegerField(db_column='A:A', default=0, verbose_name='A:A'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='AC',
            field=models.IntegerField(db_column='A:C', default=0, verbose_name='A:C'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='AG',
            field=models.IntegerField(db_column='A:G', default=0, verbose_name='A:G'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='AM',
            field=models.IntegerField(db_column='A:-', default=0, verbose_name='A:-'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='AU',
            field=models.IntegerField(db_column='A:U', default=0, verbose_name='A:U'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='CA',
            field=models.IntegerField(db_column='C:A', default=0, verbose_name='C:A'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='CC',
            field=models.IntegerField(db_column='C:C', default=0, verbose_name='C:C'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='CG',
            field=models.IntegerField(db_column='C:G', default=0, verbose_name='C:G'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='CM',
            field=models.IntegerField(db_column='C:-', default=0, verbose_name='C:-'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='CU',
            field=models.IntegerField(db_column='C:U', default=0, verbose_name='C:U'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='GA',
            field=models.IntegerField(db_column='G:A', default=0, verbose_name='G:A'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='GC',
            field=models.IntegerField(db_column='G:C', default=0, verbose_name='G:C'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='GG',
            field=models.IntegerField(db_column='G:G', default=0, verbose_name='G:G'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='GM',
            field=models.IntegerField(db_column='G:-', default=0, verbose_name='G:-'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='GU',
            field=models.IntegerField(db_column='G:U', default=0, verbose_name='G:U'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='MA',
            field=models.IntegerField(db_column='-:A', default=0, verbose_name='-:A'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='MC',
            field=models.IntegerField(db_column='-:C', default=0, verbose_name='-:C'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='MG',
            field=models.IntegerField(db_column='-:G', default=0, verbose_name='-:G'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='MM',
            field=models.IntegerField(db_column='-:-', default=0, verbose_name='-:-'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='MU',
            field=models.IntegerField(db_column='-:U', default=0, verbose_name='-:U'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='UA',
            field=models.IntegerField(db_column='U:A', default=0, verbose_name='U:A'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='UC',
            field=models.IntegerField(db_column='U:C', default=0, verbose_name='U:C'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='UG',
            field=models.IntegerField(db_column='U:G', default=0, verbose_name='U:G'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='UM',
            field=models.IntegerField(db_column='U:-', default=0, verbose_name='U:-'),
        ),
        migrations.AlterField(
            model_name='freq',
            name='UU',
            field=models.IntegerField(db_column='U:U', default=0, verbose_name='U:U'),
        ),
    ]
