# Generated by Django 2.0.6 on 2018-08-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_auto_20180804_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freq',
            name='feature',
        ),
    ]
