# Generated by Django 2.0.6 on 2018-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0014_remove_freq_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trna',
            name='p8_14',
            field=models.CharField(default='-:-', max_length=3, verbose_name='8:14'),
        ),
    ]
