# Generated by Django 2.0.6 on 2018-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0017_auto_20180806_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trna',
            name='assembly',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trna',
            name='dbname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trna',
            name='seqname',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trna',
            name='varietas',
            field=models.CharField(max_length=150),
        ),
    ]
