# Generated by Django 2.0.6 on 2018-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_auto_20180806_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consensus',
            name='clade',
        ),
        migrations.RemoveField(
            model_name='consensus',
            name='rank',
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
