# Generated by Django 2.0.6 on 2018-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0019_auto_20180806_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='consensus',
            name='clade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consensus',
            name='rank',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trna',
            name='species',
            field=models.CharField(max_length=10),
        ),
    ]
