# Generated by Django 2.0.6 on 2018-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0020_auto_20180806_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trna',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
