# Generated by Django 2.0.6 on 2018-08-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0022_auto_20180806_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freq',
        ),
    ]
