# Generated by Django 2.0.6 on 2018-08-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0023_delete_freq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.CharField(max_length=10)),
                ('isotype', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=10)),
                ('total', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('U', models.IntegerField(default=0)),
                ('absent', models.IntegerField(db_column='-', default=0)),
                ('AU', models.IntegerField(db_column='A:U', default=0, verbose_name='A:U')),
                ('UA', models.IntegerField(db_column='U:A', default=0, verbose_name='U:A')),
                ('GC', models.IntegerField(db_column='G:C', default=0, verbose_name='G:C')),
                ('CG', models.IntegerField(db_column='C:G', default=0, verbose_name='C:G')),
                ('GU', models.IntegerField(db_column='G:U', default=0, verbose_name='G:U')),
                ('UG', models.IntegerField(db_column='U:G', default=0, verbose_name='U:G')),
                ('MM', models.IntegerField(db_column='-:-', default=0, verbose_name='-:-')),
                ('AA', models.IntegerField(db_column='A:A', default=0, verbose_name='A:A')),
                ('AC', models.IntegerField(db_column='A:C', default=0, verbose_name='A:C')),
                ('AG', models.IntegerField(db_column='A:G', default=0, verbose_name='A:G')),
                ('CA', models.IntegerField(db_column='C:A', default=0, verbose_name='C:A')),
                ('CC', models.IntegerField(db_column='C:C', default=0, verbose_name='C:C')),
                ('CU', models.IntegerField(db_column='C:U', default=0, verbose_name='C:U')),
                ('GA', models.IntegerField(db_column='G:A', default=0, verbose_name='G:A')),
                ('GG', models.IntegerField(db_column='G:G', default=0, verbose_name='G:G')),
                ('UC', models.IntegerField(db_column='U:C', default=0, verbose_name='U:C')),
                ('UU', models.IntegerField(db_column='U:U', default=0, verbose_name='U:U')),
                ('AM', models.IntegerField(db_column='A:-', default=0, verbose_name='A:-')),
                ('MA', models.IntegerField(db_column='-:A', default=0, verbose_name='-:A')),
                ('CM', models.IntegerField(db_column='C:-', default=0, verbose_name='C:-')),
                ('MC', models.IntegerField(db_column='-:C', default=0, verbose_name='-:C')),
                ('GM', models.IntegerField(db_column='G:-', default=0, verbose_name='G:-')),
                ('MG', models.IntegerField(db_column='-:G', default=0, verbose_name='-:G')),
                ('UM', models.IntegerField(db_column='U:-', default=0, verbose_name='U:-')),
                ('MU', models.IntegerField(db_column='-:U', default=0, verbose_name='-:U')),
            ],
        ),
    ]
