# Generated by Django 2.0.6 on 2018-08-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0024_freq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consensus',
        ),
    ]
