# Generated by Django 2.0.6 on 2018-09-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0030_auto_20180917_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
