# Generated by Django 2.0.6 on 2018-09-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0031_delete_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
    ]
