# Generated by Django 2.0.6 on 2018-09-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0032_taxonomy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
