# Generated by Django 2.0.6 on 2018-09-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0033_delete_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=20)),
                ('taxid', models.CharField(max_length=10)),
            ],
        ),
    ]
