# Generated by Django 2.0.6 on 2018-09-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0034_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='domain',
            field=models.CharField(default='arch', max_length=4),
            preserve_default=False,
        ),
    ]
