# Generated by Django 2.0.6 on 2018-09-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0035_taxonomy_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tRNA',
        ),
    ]
