# Generated by Django 2.0.6 on 2018-09-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0037_trna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trna',
            name='domain',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='genus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='kingdom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='phylum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='subclass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='subkingdom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='subphylum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='taxclass',
            field=models.CharField(blank=True, db_column='class', max_length=50, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='trna',
            name='taxid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='varietas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
