# Generated by Django 2.0.6 on 2018-09-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0038_auto_20180918_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trna',
            name='varietas',
        ),
    ]
