# Generated by Django 2.0.6 on 2018-09-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0039_remove_trna_varietas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tRNA',
        ),
    ]
