# Generated by Django 2.0.6 on 2018-10-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0041_trna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trna',
            old_name='stemGC',
            new_name='GCcontent',
        ),
    ]
