# Generated by Django 2.0.6 on 2018-10-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0042_auto_20181009_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
