# Generated by Django 2.0.6 on 2018-10-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0043_delete_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=20)),
                ('taxid', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=20)),
                ('kingdom', models.CharField(blank=True, max_length=10, null=True)),
                ('subkingdom', models.CharField(blank=True, max_length=10, null=True)),
                ('phylum', models.CharField(blank=True, max_length=10, null=True)),
                ('subphylum', models.CharField(blank=True, max_length=10, null=True)),
                ('taxclass', models.CharField(blank=True, db_column='class', max_length=10, null=True, verbose_name='class')),
                ('subclass', models.CharField(blank=True, max_length=10, null=True)),
                ('order', models.CharField(blank=True, max_length=10, null=True)),
                ('family', models.CharField(blank=True, max_length=10, null=True)),
                ('genus', models.CharField(blank=True, max_length=10, null=True)),
                ('species', models.CharField(blank=True, max_length=10, null=True)),
                ('assembly', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
