# Generated by Django 2.0.6 on 2018-10-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0044_taxonomy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tRNA',
        ),
    ]
