# Generated by Django 2.0.6 on 2018-10-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0046_trna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consensus',
        ),
        migrations.DeleteModel(
            name='Freq',
        ),
    ]
