# Generated by Django 2.0.6 on 2018-10-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0048_consensus_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trna',
            name='best_model',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='trna',
            name='isotype',
            field=models.CharField(max_length=5),
        ),
    ]
