# Generated by Django 2.0.6 on 2018-11-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0049_auto_20181018_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consensus',
        ),
    ]
