# Generated by Django 2.0.6 on 2018-11-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0051_consensus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freq',
            old_name='absent',
            new_name='Absent',
        ),
    ]
