# Generated by Django 5.2.11 on 2026-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0052_auto_20181107_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxid',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='trna',
            name='anticodon',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='trna',
            name='assembly',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='best_model',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='trna',
            name='domain',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trna',
            name='family',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='genus',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='isotype',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='trna',
            name='kingdom',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='order',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='phylum',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='score',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='species',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trna',
            name='taxclass',
            field=models.CharField(blank=True, db_column='class', db_index=True, max_length=10, null=True, verbose_name='class'),
        ),
        migrations.AddIndex(
            model_name='consensus',
            index=models.Index(fields=['taxid', 'isotype', 'datatype'], name='idx_consensus_taxid_iso_dt'),
        ),
        migrations.AddIndex(
            model_name='freq',
            index=models.Index(fields=['taxid', 'isotype'], name='idx_freq_taxid_isotype'),
        ),
    ]
