ISOTYPES = (
  ('Ala', 'Ala'),
  ('Arg', 'Arg'),
  ('Asn', 'Asn'),
  ('Asp', 'Asp'),
  ('Cys', 'Cys'),
  ('Gln', 'Gln'),
  ('Glu', 'Glu'),
  ('Gly', 'Gly'),
  ('His', 'His'),
  ('Ile', 'Ile'),
  ('iMet', 'iMet'),
  ('Leu', 'Leu'),
  ('Lys', 'Lys'),
  ('Met', 'Met'),
  ('Phe', 'Phe'),
  ('Pro', 'Pro'),
  ('Ser', 'Ser'),
  ('SeC', 'SeC'),
  ('Thr', 'Thr'),
  ('Trp', 'Trp'),
  ('Tyr', 'Tyr'),
  ('Val', 'Val')
)

